mediatek/base/power/udi_v2: Fix possible overflow in the destination buffer
Build log:

CC      drivers/misc/mediatek/base/power/udi_v2/mtk_udi.o
../drivers/misc/mediatek/base/power/udi_v2/mtk_udi.c:481:18: error: 'sscanf' may overflow; destination buffer in argument 9 has size 512, but the corresponding specifier may
require size 513 [-Werror,-Wfortify-source]
                        &recv_buf[2], recv_char[1], &recv_buf[4]) == 8) {
                                      ^
../drivers/misc/mediatek/base/power/udi_v2/mtk_udi.c:488:18: error: 'sscanf' may overflow; destination buffer in argument 8 has size 512, but the corresponding specifier may
require size 513 [-Werror,-Wfortify-source]
                        &recv_buf[2], recv_char[1]) == 6) {
                                      ^

Signed-off-by: Rem01Gaming <Rem01_Gaming@proton.me>